{% set name = "tsml-eval" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3d582451dad3ea9fad80dfabb53b18cebc5f964ef32d5fceec487706d7a62296

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - setuptools >=61
    - wheel
    - toml
    - python-build
    - pip
  run:
    - python >=3.8,<3.12
    - aeon >=0.6.0,<0.7.0
    - scikit-learn >=1.0.2,<=1.3.2
    - tsml >=0.2.1,<0.3.0
    - matplotlib-base
    - gpustat
    - psutil

test:
  imports:
    - tsml_eval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/time-series-machine-learning/tsml-eval/
  dev_url: https://github.com/time-series-machine-learning/
  summary: A package for benchmarking time series machine learning tools.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MatthewMiddlehurst
