{% set name = "tsml-eval" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsml-eval-{{ version }}.tar.gz
  sha256: a92287d4c5ea8647e4bf976fc661323a54b7526d24b4581c26db44f8d119e6e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - setuptools >=61
    - wheel
    - toml
    - python-build
    - pip
  run:
    - python >=3.8,<3.12
    - aeon >=0.4.0,<0.5.0
    - scikit-learn >=1.0.2,<=1.2.2
    - tsml >=0.2.0,<0.3.0
    - gpustat
    - psutil

test:
  imports:
    - tsml_eval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/time-series-machine-learning/tsml-eval/
  dev_url: https://github.com/time-series-machine-learning/
  summary: A package for benchmarking time series machine learning tools.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MatthewMiddlehurst
