{% set name = "tsml-eval" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5320f7d87d438a22ab13054d646902500b73b8c0da867854ee83e7772e5abb88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - setuptools >=61
    - wheel
    - toml
    - python-build
    - pip
  run:
    - python >=3.8,<3.13
    - aeon >=0.8.0,<0.9.0
    - tsml >=0.4.0,<0.5.0
    - scikit-learn >=1.0.0,<=1.5.0
    - matplotlib-base
    - gpustat
    - psutil

test:
  imports:
    - tsml_eval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/time-series-machine-learning/tsml-eval/
  dev_url: https://github.com/time-series-machine-learning/
  summary: A package for benchmarking time series machine learning tools.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MatthewMiddlehurst
